// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Project struct {
	ID         int64
	Name       string
	Path       string
	LastOpened sql.NullTime
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
