// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2) {
  return window['go']['main']['App']['AddProject'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DestroyTerminal(arg1) {
  return window['go']['main']['App']['DestroyTerminal'](arg1);
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetEditorConfig() {
  return window['go']['main']['App']['GetEditorConfig']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetProjectFiles(arg1) {
  return window['go']['main']['App']['GetProjectFiles'](arg1);
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleInput(arg1, arg2) {
  return window['go']['main']['App']['HandleInput'](arg1, arg2);
}

export function LoadDirectoryContents(arg1) {
  return window['go']['main']['App']['LoadDirectoryContents'](arg1);
}

export function OpenConfigFile() {
  return window['go']['main']['App']['OpenConfigFile']();
}

export function OpenProjectFolder() {
  return window['go']['main']['App']['OpenProjectFolder']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2);
}
